Repository COS301-SE-2022/Gym-King, pull requests merged in 2022-07, with the labels that each got.

#149 🍱 adding Entity
  back-end/src/entities/badge.entity.ts
  back-end/src/entities/badge_claim.entity.ts
  back-end/src/entities/badge_owned.entity.ts
Labels: enhancement, role:service-engineer, role:api-engineer, priority:low, scope:api, status:ready, type:feature

#151 Feature create badge
  .gitignore
  front-end/.gitignore
  front-end/package-lock.json
  front-end/package.json
  front-end/public/assets/badges/emblem/bicep.png
  front-end/public/assets/badges/emblem/clean.png
  front-end/public/assets/badges/emblem/cycle.png
  front-end/public/assets/badges/emblem/dumbell.png
  front-end/public/assets/badges/emblem/gym.png
  front-end/public/assets/badges/emblem/pullup.png
  front-end/public/assets/badges/emblem/running.png
  front-end/public/assets/badges/emblem/situp.png
  front-end/public/assets/badges/emblem/treadmill.png
  front-end/public/assets/badges/rank/bronze.png
  front-end/public/assets/badges/rank/gold.png
  front-end/public/assets/badges/rank/silver.png
  front-end/src/badges/emblem/bicep.png
  front-end/src/badges/emblem/clean.png
  front-end/src/badges/emblem/cycle.png
  front-end/src/badges/emblem/dumbell.png
  front-end/src/badges/emblem/gym.png
  front-end/src/badges/emblem/path37385.png
  front-end/src/badges/emblem/pullup.png
  front-end/src/badges/emblem/running.png
  front-end/src/badges/emblem/situp.png
  front-end/src/badges/emblem/treadmill.png
  front-end/src/badges/rank/bronze.png
  front-end/src/badges/rank/gold.png
  front-end/src/badges/rank/silver.png
  front-end/src/components/BadgeCanvas/BadgeCanvas.css
  front-end/src/components/BadgeCanvas/BadgeCanvas.tsx
  front-end/src/components/BadgeSlider/BadgeSlider.css
  front-end/src/components/BadgeSlider/BadgeSlider.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  package.json
  yarn.lock
Labels: enhancement, role:ui-engineer, role:designer, priority:medium, scope:ui, status:on-hold, type:change, type:cosmetic, type:enhance

#153 ✨ Add Burger menu component
  front-end/src/components/BurgerMenu/BurgerMenu.css
  front-end/src/components/BurgerMenu/BurgerMenu.tsx
  front-end/src/components/toolbar/Toolbar.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
Labels: priority:medium, scope:ui, status:needs-tests, status:ready, type:enhance, needs review!

#152 Feature-Map
  front-end/src/components/map/MapView.tsx
Labels: priority:high, scope:ui, status:ready, type:change, needs review!

#155 Feature map
  front-end/src/components/map/MapView.css
  front-end/src/components/map/MapView.tsx
  front-end/src/icons/gym.png
  front-end/src/icons/location.png
  front-end/src/icons/recenter.png
  package.json
  yarn.lock
Labels: priority:medium, scope:ui, status:on-hold, status:ready, type:change, type:cosmetic, type:feature, needs review!

#157 ✨ Feature: create manage gyms
  front-end/src/components/GymCard/GymCard.css
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/pages/ManageGyms/ManageGyms.css
  front-end/src/pages/ManageGyms/ManageGyms.tsx
Labels: priority:high, scope:ui, status:needs-tests, status:not-ready, type:feature, needs review!

#160 added navigation
  front-end/src/App.tsx
  front-end/src/components/BurgerMenu/BurgerMenu.css
  front-end/src/components/BurgerMenu/BurgerMenu.tsx
  front-end/src/components/toolbar/Toolbar.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
  front-end/src/pages/MyBadge/MyBadge.tsx
  front-end/src/pages/UserMap/UserMap.tsx
Labels: priority:high, scope:ui, status:ready, type:change, type:enhance, needs review!

#161 🐛 fix AR selector for badge slider
  front-end/src/components/AR/AR.tsx
  front-end/src/components/BadgeSlider/BadgeSlider.tsx
  front-end/src/pages/ARPage/ARPage.tsx
Labels: help wanted, scope:ar, priority:high, scope:ui, status:on-hold, type:change, type:fix, needs review!

#163 Updated UI
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.css
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/ActivityList/ActivityList.tsx
  front-end/src/components/LeaderBoardSwiper/LeaderBoardValues/LeaderboardValues.css
  front-end/src/components/LeaderBoardSwiper/LeaderBoardValues/LeaderboardValues.tsx
  front-end/src/components/LeaderBoardSwiper/LeaderboardSwiper.css
  front-end/src/components/LeaderBoardSwiper/LeaderboardSwiper.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/Leaderboard/Leaderboard.css
  front-end/src/pages/Leaderboard/Leaderboard.tsx
  front-end/src/pages/LoginPage/Login.css
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/theme/variables.css
Labels: priority:low, scope:ui, status:needs-tests, type:cosmetic, type:enhance, needs review!

#166 👽️Updating API calls for front end
  back-end/src/employees/employees.ts
  back-end/src/repositories/badge.repository.ts
  front-end/src/pages/EditBadgePage/EditBadge.tsx
Labels: priority:low, scope:api, status:needs-tests, type:change, needs review!

#165 Updated Login/Register
  front-end/src/pages/LoginPage/Login.tsx
Labels: priority:high, priority:medium, scope:api, scope:ui, status:needs-tests, type:enhance, type:fix, needs review!

#172 Add gym owner page
  front-end/src/pages/GymOwnerPage/GymOwnerPage.css
  front-end/src/pages/GymOwnerPage/GymOwnerPage.tsx
Labels: priority:medium, scope:ui, status:needs-tests, status:on-hold, type:cosmetic, type:feature, needs review!

#173 Add feature manage employees
  front-end/src/components/EmployeeCard/EmployeeCard.css
  front-end/src/components/EmployeeCard/EmployeeCard.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.css
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
Labels: priority:medium, scope:ui, status:needs-tests, status:on-hold, type:cosmetic, type:feature, needs review!

#174 Create UserProfile
  front-end/src/App.tsx
  front-end/src/pages/Profile/UserProfile.css
  front-end/src/pages/Profile/UserProfile.tsx
  front-end/src/theme/variables.css
Labels: priority:medium, scope:ui, status:needs-tests, type:cosmetic, type:feature, needs review!

#167 👽️Updating API calls for front end
  back-end/src/employees/employees.ts
  back-end/src/entities/gym_owned.entity.ts
  back-end/src/owners/owners.ts
  back-end/src/repositories/badge_claim.repository.ts
  back-end/src/repositories/badge_owned.repository.ts
  back-end/src/repositories/gym_owned.repository.ts
  front-end/src/pages/EditBadgePage/EditBadge.tsx
Labels: priority:low, scope:api, status:needs-tests, type:change, needs review!

#176 Created EmployeeProfile
  front-end/src/App.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.css
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/UserProfile/UserProfile.css
  front-end/src/pages/UserProfile/UserProfile.tsx
Labels: priority:medium, scope:ui, status:needs-tests, type:cosmetic, type:feature, needs review!

#177 Created OwnerProfile
  front-end/src/App.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.css
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
Labels: priority:medium, scope:ui, status:needs-tests, type:cosmetic, type:feature, needs review!

#178 add editGym page
  front-end/src/App.tsx
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/pages/EditGymPage/EditGym.css
  front-end/src/pages/EditGymPage/EditGym.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/GymOwnerPage/GymOwnerPage.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
  front-end/src/pages/UserMap/UserMap.tsx
Labels: priority:low, scope:ui, status:not-ready, type:change, type:feature, needs review!

#175 Feature map
  front-end/src/components/map/MapView.css
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/UserMap/UserMap.css
Labels: priority:medium, scope:ui, status:not-ready, status:on-hold, type:enhance, type:feature

#180 🧱 Changing API calls and repository
  back-end/src/owners/owners.ts
  back-end/src/repositories/badge.repository.ts
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/EditGymPage/EditGym.tsx
Labels: priority:low, scope:api, status:needs-tests, type:change, needs review!

#181 change code for add gym
  front-end/src/components/GymCard/GymCard.css
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
Labels: priority:high, scope:ui, status:needs-tests, status:not-ready, type:change, type:refactor, needs review!

#179 Feature map
  front-end/src/App.tsx
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/GymPage/GymPage.css
  front-end/src/pages/GymPage/GymPage.tsx
  front-end/src/pages/Leaderboard/Leaderboard.tsx
Labels: priority:low, scope:ui, status:on-hold, type:change

#182 🧱New APIs for user OTP and repository and entity.
  back-end/src/entities/user_otp.entity.ts
  back-end/src/repositories/gym_user.repository.ts
  back-end/src/repositories/user_otp.repository.ts
  back-end/src/users/users.ts
  back-end/src/utils/utils.ts
Labels: priority:high, scope:api, status:needs-tests, type:feature, needs review!

#183 🧱Adding OTP functionality to users.
  back-end/src/repositories/badge_claim.repository.ts
  back-end/src/repositories/badge_owned.repository.ts
  back-end/src/users/users.ts
Labels: priority:high, scope:api, status:needs-tests, type:feature, needs review!

#185 🧱Adding OTP functionality to employees.
  back-end/src/assets/models/ANDROID/b_bicep.glb
  back-end/src/assets/models/ANDROID/b_clean.glb
  back-end/src/assets/models/ANDROID/b_cycle.glb
  back-end/src/assets/models/ANDROID/b_dumbell.glb
  back-end/src/assets/models/ANDROID/b_gym.glb
  back-end/src/assets/models/ANDROID/b_pullup.glb
  back-end/src/assets/models/ANDROID/b_run.glb
  back-end/src/assets/models/ANDROID/b_situp.glb
  back-end/src/assets/models/ANDROID/b_treadmill.glb
  back-end/src/assets/models/ANDROID/g_bicep.glb
  back-end/src/assets/models/ANDROID/g_clean.glb
  back-end/src/assets/models/ANDROID/g_cycle.glb
  back-end/src/assets/models/ANDROID/g_dumbell.glb
  back-end/src/assets/models/ANDROID/g_gym.glb
  back-end/src/assets/models/ANDROID/g_pullup.glb
  back-end/src/assets/models/ANDROID/g_run.glb
  back-end/src/assets/models/ANDROID/g_situp.glb
  back-end/src/assets/models/ANDROID/g_treadmill.glb
  back-end/src/assets/models/ANDROID/s_bicep.glb
  back-end/src/assets/models/ANDROID/s_clean.glb
  back-end/src/assets/models/ANDROID/s_cycle.glb
  back-end/src/assets/models/ANDROID/s_dumbell.glb
  back-end/src/assets/models/ANDROID/s_gym.glb
  back-end/src/assets/models/ANDROID/s_pullup.glb
  back-end/src/assets/models/ANDROID/s_run.glb
  back-end/src/assets/models/ANDROID/s_situp.glb
  back-end/src/assets/models/ANDROID/s_treadmill.glb
  back-end/src/assets/models/IOS/b_bicep.usdz
  back-end/src/assets/models/IOS/b_clean.usdz
  back-end/src/assets/models/IOS/b_cycle.usdz
  back-end/src/assets/models/IOS/b_dumbell.usdz
  back-end/src/assets/models/IOS/b_gym.usdz
  back-end/src/assets/models/IOS/b_pullup.usdz
  back-end/src/assets/models/IOS/b_run.usdz
  back-end/src/assets/models/IOS/b_situp.usdz
  back-end/src/assets/models/IOS/b_treadmill.usdz
  back-end/src/assets/models/IOS/g_bicep.usdz
  back-end/src/assets/models/IOS/g_clean.usdz
  back-end/src/assets/models/IOS/g_cycle.usdz
  back-end/src/assets/models/IOS/g_dumbell.usdz
  back-end/src/assets/models/IOS/g_gym.usdz
  back-end/src/assets/models/IOS/g_pullup.usdz
  back-end/src/assets/models/IOS/g_run.usdz
  back-end/src/assets/models/IOS/g_situp.usdz
  back-end/src/assets/models/IOS/g_treadmill.usdz
  back-end/src/assets/models/IOS/s_bicep.usdz
  back-end/src/assets/models/IOS/s_clean.usdz
  back-end/src/assets/models/IOS/s_cycle.usdz
  back-end/src/assets/models/IOS/s_dumbell.usdz
  back-end/src/assets/models/IOS/s_gym.usdz
  back-end/src/assets/models/IOS/s_pullup.usdz
  back-end/src/assets/models/IOS/s_run.usdz
  back-end/src/assets/models/IOS/s_situp.usdz
  back-end/src/assets/models/IOS/s_treadmill.usdz
  back-end/src/employees/employees.ts
  back-end/src/entities/employee_otp.entity.ts
  back-end/src/repositories/employee_otp.repository.ts
  back-end/src/repositories/gym_employee.repository.ts
  back-end/src/users/users.ts
Labels: priority:high, scope:api, status:needs-tests, type:change, type:feature, needs review!

#186 Updated Login
  front-end/src/pages/EmployeeProfile/EmployeeProfile.css
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/theme/variables.css
  package.json
  yarn.lock
Labels: priority:low, scope:api, scope:ui, status:needs-tests, type:enhance, type:fix, needs review!

#192 Updated Accept/Reject UI
  front-end/src/components/AR/AR.tsx
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/ActivityList/ActivityList.css
  front-end/src/components/ActivityList/ActivityList.tsx
  front-end/src/components/BadgeCanvas/BadgeCanvas.css
  front-end/src/components/BadgeSlider/BadgeSlider.css
  front-end/src/components/BadgeSlider/BadgeSlider.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.css
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/components/MyBadgeGrid/MyBadgeCard/MyBadgeCard.css
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/components/radioGroup/radioGroup.tsx
  front-end/src/components/segmentButton/segmentButton.tsx
  front-end/src/pages/AddGym/AddGym.css
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.css
  front-end/src/pages/CreateBadgePage/CreateBadge.test.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/EditGymPage/EditGym.css
  front-end/src/pages/EditGymPage/EditGym.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.css
  front-end/src/theme/variables.css
Labels: priority:medium, scope:ui, status:needs-tests, type:cosmetic, type:enhance, needs review!

#193 🧱New API and changes to entity and repositories.
  back-end/src/entities/gym_employee.entity.ts
  back-end/src/owners/owners.ts
  back-end/src/repositories/badge.repository.ts
  back-end/src/repositories/badge_claim.repository.ts
  back-end/src/repositories/badge_owned.repository.ts
  back-end/src/repositories/gym_owner.repository.ts
  front-end/src/pages/UserPendingBadges/PendingBadges.tsx
  front-end/src/pages/UserProfile/UserProfile.tsx
Labels: priority:medium, scope:api, status:needs-tests, type:change, type:feature

#194 Updated OwnerProfile
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
Labels: priority:low, scope:api, scope:ui, status:needs-tests, type:feature, needs review!

#188 Add AddEmployee feature
  front-end/src/pages/AddEmployee/AddEmployee.css
  front-end/src/pages/AddEmployee/AddEmployee.tsx
Labels: priority:medium, scope:ui, status:needs-tests, status:ready, type:feature, needs review!

#195 Updated UploadActivity UI
  front-end/src/components/activityInputs/ActivityInputs.css
  front-end/src/components/activityInputs/ActivityInputs.test.tsx
  front-end/src/components/activityInputs/ActivityInputs.tsx
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/EditGymPage/EditGym.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/Leaderboard/Leaderboard.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.test.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/UserPendingBadges/PendingBadges.tsx
  front-end/src/pages/UserProfile/UserProfile.css
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
  front-end/src/theme/variables.css
Labels: priority:low, scope:ui, status:needs-tests, type:cosmetic, needs review!

#205 Added basic test for AppSettingsPage
  front-end/src/pages/AppSettingsPage/AppSettingsPage.test.tsx
Labels: priority:low, status:ready, type:test, scope:admin, needs review!

#200 Add basic test for GymOwnerPage
  front-end/src/pages/GymOwnerPage/GymOwnerPage.test.tsx
Labels: priority:low, status:ready, type:test, scope:admin, needs review!

#203 Feature owner profile
  front-end/src/pages/OwnerProfile/OwnerProfile.test.tsx
Labels: priority:low, status:ready, type:test, scope:admin, needs review!

#197 Removed redundant code
  front-end/src/pages/SplashPage/SplashPage.test.tsx
  front-end/src/pages/SplashPage/SplashPage.tsx
Labels: priority:low, scope:ui, status:needs-tests, status:ready, type:change, type:chore

#199 Feature manage employees
  front-end/src/pages/ManageEmployees/ManageEmployees.test.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
Labels: help wanted, priority:medium, scope:api, scope:ui, status:needs-info, status:needs-tests, status:ready, type:change, type:chore, needs review!

#202 Add basic test for ManageGyms
  front-end/src/pages/ManageGyms/ManageGyms.test.tsx
Labels: priority:low, status:ready, type:test, scope:admin, needs review!

#198 Added API call
  front-end/src/pages/AddEmployee/AddEmployee.test.tsx
  front-end/src/pages/AddEmployee/AddEmployee.tsx
Labels: help wanted, priority:medium, scope:api, scope:db, status:needs-tests, status:ready, type:change

#201 Added basic test from EmployeeProfile
  front-end/src/pages/EmployeeProfile/EmployeeProfile.test.tsx
Labels: priority:low, status:ready, type:test, scope:admin, needs review!

#207 Fixed GymPage Navigation
  front-end/src/components/map/MapView.css
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/GymPage/GymPage.css
  front-end/src/pages/GymPage/GymPage.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
  front-end/src/theme/variables.css
Labels: priority:low, scope:ui, status:needs-tests, type:cosmetic, type:enhance, needs review!

#208 Added navigation to UploadActivityPage
  front-end/src/App.tsx
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/ActivityList/ActivityList.tsx
  front-end/src/components/BurgerMenu/BurgerMenu.tsx
  front-end/src/components/EmployeeCard/EmployeeCard.tsx
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/components/approvalButton/approvalButton.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.css
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
  front-end/src/pages/GymOwnerPage/GymOwnerPage.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/theme/variables.css
Labels: priority:low, scope:ui, status:needs-tests, type:chore, type:enhance, type:fix, needs review!

#212 🐛Fixes stuff
  .github/workflows/nxtest.yml
  back-end/src/employees/employees.test.ts
  back-end/src/employees/employees.ts
  back-end/src/entities/badge.entity.ts
  back-end/src/entities/gym_employee.entity.ts
  back-end/src/entities/gym_owner.entity.ts
  back-end/src/entities/gym_user.entity.ts
  back-end/src/owners/owners.test.ts
  back-end/src/owners/owners.ts
  back-end/src/repositories/badge.repository.ts
  back-end/src/repositories/badge_claim.repository.ts
  back-end/src/repositories/badge_owned.repository.ts
  back-end/src/repositories/employee_otp.repository.ts
  back-end/src/repositories/gym.repository.ts
  back-end/src/repositories/gym_owned.repository.ts
  back-end/src/repositories/gym_user.repository.ts
  back-end/src/users/users.test.ts
  back-end/src/users/users.ts
  back-end/src/utils/utils.test.ts
  back-end/src/utils/utils.ts
  package.json
  yarn.lock
Labels: type:bug, priority:high, scope:api, status:needs-tests

#211 💄 view badges
  front-end/src/components/BadgeImage/BadgeImage.css
  front-end/src/components/BadgeImage/BadgeImage.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.test.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/components/MyBadgeGrid/MyBadgeCard/MyBadgeCard.tsx
  front-end/src/components/MyBadgeGrid/MyBadgeGrid.tsx
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.test.tsx
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/pages/MyBadge/MyBadge.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.test.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
Labels: priority:high, scope:ui, status:needs-tests, status:ready, type:cosmetic, type:enhance, needs review!

#210 Fixing Pages and Components
  front-end/src/App.tsx
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/pages/AddEmployee/AddEmployee.tsx
  front-end/src/pages/EditGymPage/EditGym.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
Labels: priority:high, scope:ui, status:needs-tests, type:feature, type:fix, needs review!

#216 🩹 Fixed routing
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/BurgerMenu/BurgerMenu.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/AddEmployee/AddEmployee.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
Labels: priority:high, scope:ui, status:ready, type:feature, type:fix

#213 🐛🧱Adding owner and employee firebase and fixes.
  back-end/src/employees/employees.ts
  back-end/src/firebase.connection.ts
  back-end/src/owners/owners.ts
  back-end/src/repositories/gym_employee.repository.ts
  back-end/src/repositories/gym_owner.repository.ts
  back-end/src/users/users.ts
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
Labels: priority:high, scope:api, status:needs-tests, status:ready, type:feature, type:fix

#215 Added Employee profile pictures
  front-end/src/components/toolbar/Toolbar.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.css
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/UserProfile/UserProfile.css
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/theme/variables.css
  package.json
  yarn.lock
Labels: priority:high, scope:api, scope:ui, status:needs-tests, status:ready, type:feature

#217 Feature edit badge
  front-end/src/components/BadgeCanvas/BadgeCanvas.tsx
  front-end/src/components/BadgeSlider/BadgeSlider.tsx
  front-end/src/components/MyBadgeGrid/MyBadgeGrid.tsx
  front-end/src/components/SelectGym-Map/SelectGymMap.css
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
Labels: priority:medium, scope:ui, status:on-hold, type:change

#218 ♻️ fixing dependecies
  .gitignore
  back-end/package.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/pages/OTP/OTP.tsx
  package.json
  yarn.lock
Labels: type:documentation, priority:low, status:not-ready, scope:admin

#220 🐛 add react dependency back
  front-end/src/components/AR/AR.tsx
  package.json
Labels: priority:high, scope:ui, status:not-ready, status:on-hold, type:chore, scope:admin

#223 Fixing UI
  front-end/src/components/GymCard/GymCard.css
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/PendingBadgeItem/PendingBadgeItem.tsx
  front-end/src/components/approvalButton/approvalButton.tsx
  front-end/src/components/toolbar/Toolbar.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.css
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/MyBadge/MyBadge.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.css
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/UserMap/UserMap.tsx
  front-end/src/pages/UserProfile/UserProfile.css
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/theme/variables.css
Labels: priority:medium, scope:ui, status:needs-tests, type:cosmetic, type:enhance, type:fix, needs review!

#225 🎇 Feature manage gyms
  front-end/src/components/GymCard/GymCard.test.tsx
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/pages/AddGym/AddGym.test.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.test.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.tsx
  front-end/src/pages/EditGymPage/EditGym.test.tsx
  front-end/src/pages/EditGymPage/EditGym.tsx
  front-end/src/pages/ManageGyms/ManageGyms.test.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
Labels: priority:medium, scope:ui, status:ready, type:cosmetic, type:enhance, type:test, needs review!

#221 Comments
  front-end/src/components/AR/AR.tsx
  front-end/src/components/BadgeCanvas/BadgeCanvas.tsx
  front-end/src/components/BadgeSlider/BadgeSlider.tsx
Labels: type:documentation, priority:low, status:on-hold, type:chore, type:cosmetic, scope:admin

#222 Feature api
  back-end/src/employees/employees.ts
  back-end/src/repositories/badge_claim.repository.ts
  back-end/src/users/users.ts
Labels: priority:low, scope:api, status:ready, type:change

#228 💄 added badge image to pendingBadges and uploadActivity
  front-end/src/components/BadgeImage/BadgeImage.css
  front-end/src/components/BadgeImage/BadgeImage.test.tsx
  front-end/src/components/BadgeImage/BadgeImage.tsx
  front-end/src/components/BadgeSlider/BadgeSlider.test.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/components/MyBadgeGrid/MyBadgeCard/MyBadgeCard.tsx
  front-end/src/components/PendingBadgeItem/PendingBadgeItem.test.tsx
  front-end/src/components/PendingBadgeItem/PendingBadgeItem.tsx
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/pages/MyBadge/MyBadge.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/UserPendingBadges/PendingBadges.tsx
Labels: priority:high, scope:ui, status:ready, type:cosmetic, type:enhance, needs review!

#227 ✅🧱Changing entity, datasource, server with tests.
  .github/workflows/nxtest.yml
  back-end/.gitignore
  back-end/package.json
  back-end/src/datasource.ts
  back-end/src/employees/employees.test.ts
  back-end/src/employees/employees.ts
  back-end/src/entities/badge.entity.ts
  back-end/src/index.ts
  back-end/src/owners/owners.test.ts
  back-end/src/owners/owners.ts
  back-end/src/users/users.test.ts
  back-end/src/utils/utils.test.ts
  back-end/src/utils/utils.ts
  back-end/tsconfig.json
Labels: priority:high, scope:api, status:ready, type:change, type:feature, type:test

#226 Feature fixes
  front-end/src/App.tsx
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/approvalButton/approvalButton.css
  front-end/src/components/approvalButton/approvalButton.test.tsx
  front-end/src/components/approvalButton/approvalButton.tsx
  front-end/src/components/map/MapView.tsx
  front-end/src/components/toolbar/Toolbar.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/AddEmployee/AddEmployee.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/CreateUserPage/Register.test.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/Leaderboard/Leaderboard.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
  front-end/src/pages/MyBadge/MyBadge.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/SplashPage/SplashPage.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/UserPendingBadges/PendingBadges.tsx
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.test.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
Labels: priority:medium, scope:ui, status:needs-tests, type:cosmetic, type:fix

#230 Added tests
  front-end/src/pages/AcceptRejectPage/AcceptRejectPage.test.tsx
  front-end/src/pages/AddEmployee/AddEmployee.test.tsx
  front-end/src/pages/AddGym/AddGym.test.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.test.tsx
  front-end/src/pages/CreateUserPage/Register.test.tsx
  front-end/src/pages/EditBadgePage/EditBadge.test.tsx
Labels: priority:high, scope:api, scope:ui, status:needs-tests, type:fix, type:test, needs review!

#229 Feature permissons
  capacitor.config.ts
  front-end/package.json
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/SplashPage/SplashPage.tsx
  package.json
Labels: priority:high, scope:ui, status:on-hold, status:ready, type:change, type:cosmetic

#231 add new map style to edit gym page
  front-end/src/App.tsx
  front-end/src/pages/EditGymPage/EditGym.tsx
Labels: type:bug, help wanted, invalid?, scope:ar, priority:high, status:needs-info, type:change

#233 UI fixes
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/ActivityList/ActivityList.test.tsx
  front-end/src/components/ActivityList/ActivityList.tsx
  front-end/src/components/EmployeeList/EmployeeList.test.tsx
  front-end/src/components/EmployeeList/EmployeeList.tsx
  front-end/src/components/GymCard/GymCard.css
  front-end/src/components/GymCard/GymCard.test.tsx
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.test.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.test.tsx
  front-end/src/components/activityInputs/ActivityInputs.test.tsx
  front-end/src/components/activityInputs/ActivityInputs.tsx
  front-end/src/components/map/MapView.css
  front-end/src/components/map/MapView.tsx
  front-end/src/components/toolbar/Toolbar.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/EditGymPage/EditGym.test.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.test.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.test.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.test.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/GymPage/GymPage.test.tsx
  front-end/src/pages/Leaderboard/Leaderboard.test.tsx
  front-end/src/pages/LoginPage/Login.test.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.test.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
  front-end/src/pages/ManageGyms/ManageGyms.test.tsx
  front-end/src/pages/MyBadge/MyBadge.test.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.test.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.test.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.test.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/UserPendingBadges/PendingBadges.test.tsx
  front-end/src/pages/UserProfile/UserProfile.test.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.test.tsx
  front-end/src/theme/variables.css
Labels: priority:medium, scope:ui, status:needs-tests, status:next-release, type:cosmetic, type:fix, needs review!

#236 Fixed bug
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
Labels: priority:low, scope:ui, status:ready, type:cosmetic, type:fix, needs review!
