Repository COS301-SE-2022/Gym-King, pull requests merged in 2022-09, with the labels that each got.

#242 Feature fixes
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.tsx
  front-end/src/components/map/MapView.tsx
  front-end/src/config.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/AddEmployee/AddEmployee.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/CreateUserPage/Register.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/EditGymPage/EditGym.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/Leaderboard/Leaderboard.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
  front-end/src/pages/MyBadge/MyBadge.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/UserPendingBadges/PendingBadges.tsx
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
Labels: priority:medium, scope:api, scope:ui, status:needs-tests, type:change, type:fix, needs review!

#243 Working on Build
  back-end/src/employees/employees.ts
  back-end/src/owners/owners.ts
  back-end/src/users/users.ts
  back-end/src/utils/utils.ts
  front-end/capacitor.config.ts
  front-end/package.json
  front-end/src/components/BurgerMenu/BurgerMenu.tsx
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/CreateUserPage/Register.css
  front-end/src/pages/CreateUserPage/Register.tsx
  front-end/src/pages/LoginPage/Login.css
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/OTP/OTP.css
  front-end/src/pages/OTP/OTP.tsx
  front-end/src/pages/SplashPage/SplashPage.tsx
  package.json
Labels: priority:low, scope:ui, status:on-hold, type:change, type:fix

#248 User Map - Search Bar feature
  back-end/src/entities/badge_claim.entity.ts
  back-end/src/users/users.ts
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/components/GymSearchBar/GymSearchBar.tsx
  front-end/src/components/map/MapView.css
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/UserMap/UserMap.css
  front-end/src/pages/UserMap/UserMap.tsx
  package.json
Labels: priority:low, scope:ui, status:not-ready, type:enhance, type:feature

#241 🧱Working on EMAIL OTP system!
  back-end/.gitignore
  back-end/jest.config.js
  back-end/package.json
  back-end/src/datasource.ts
  back-end/src/employees/employees.test.ts
  back-end/src/employees/employees.ts
  back-end/src/entities/badge_claim.entity.ts
  back-end/src/owners/owners.test.ts
  back-end/src/owners/owners.ts
  back-end/src/users/users.test.ts
  back-end/src/users/users.ts
  back-end/src/utils/utils.ts
Labels: priority:low, scope:api, status:ready, type:fix, needs review!

#251 Feature api social feature(back-end)
  back-end/src/employees/employees.test.ts
  back-end/src/employees/employees.ts
  back-end/src/entities/badge.entity.ts
  back-end/src/entities/employee_otp.entity.ts
  back-end/src/entities/friend.entity.ts
  back-end/src/entities/gym_employee.entity.ts
  back-end/src/entities/gym_owner.entity.ts
  back-end/src/entities/gym_user.entity.ts
  back-end/src/entities/owner_otp.entity.ts
  back-end/src/entities/subscription.entity.ts
  back-end/src/entities/user_otp.entity.ts
  back-end/src/owners/owners.test.ts
  back-end/src/owners/owners.ts
  back-end/src/repositories/friend.repository.ts
  back-end/src/repositories/subscription.repository.ts
  back-end/src/users/users.test.ts
  back-end/src/users/users.ts
  back-end/src/utils/utils.ts
Labels: priority:high, scope:api, status:needs-tests, status:not-ready, status:on-hold, type:feature, needs review!

#252 Feature ar
  front-end/package.json
  front-end/src/components/AR/AR.tsx
  front-end/src/components/AR/compatibleDevices.tsx
  package.json
Labels: scope:ar, priority:high, scope:ui, status:on-hold, type:change, needs review!

#259 🚧 add generic build for nx build --affected workflow
  front-end/package.json
Labels: priority:low, scope:db, status:ready, type:chore, type:fix

#250 Register page redo
  front-end/src/App.tsx
  front-end/src/components/EmployeeCard/EmployeeCard.css
  front-end/src/components/EmployeeCard/EmployeeCard.test.tsx
  front-end/src/components/EmployeeCard/EmployeeCard.tsx
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/GymSearchBar/GymSearchBar.tsx
  front-end/src/components/Register/Contact.tsx
  front-end/src/components/Register/Gym.tsx
  front-end/src/components/Register/Identifications.tsx
  front-end/src/components/Register/Password.tsx
  front-end/src/components/Register/RegisterForm.tsx
  front-end/src/components/dropdown/dropdown.css
  front-end/src/components/dropdown/dropdown.tsx
  front-end/src/pages/AddEmployee/AddEmployee.css
  front-end/src/pages/AddEmployee/AddEmployee.test.tsx
  front-end/src/pages/AddEmployee/AddEmployee.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/CreateUserPage/Register.css
  front-end/src/pages/CreateUserPage/Register.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/EditGymPage/EditGym.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
  front-end/src/pages/Leaderboard/Leaderboard.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/UserPendingBadges/PendingBadges.tsx
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/theme/variables.css
  front-end/src/utils/validation.tsx
  package.json
Labels: priority:high, priority:medium, scope:ui, status:needs-tests, type:change, type:enhance, type:feature, needs review!

#260 ♻️✅🧱Additions,Changes,Tests
  back-end/.gitignore
  back-end/package.json
  back-end/src/employees/employees.test.ts
  back-end/src/employees/employees.ts
  back-end/src/entities/badge.entity.ts
  back-end/src/entities/gym.entity.ts
  back-end/src/entities/gym_brand.entity.ts
  back-end/src/entities/gym_employee.entity.ts
  back-end/src/entities/gym_owner.entity.ts
  back-end/src/entities/gym_user.entity.ts
  back-end/src/firebase.connection.ts
  back-end/src/owners/owners.test.ts
  back-end/src/owners/owners.ts
  back-end/src/repositories/badge.repository.ts
  back-end/src/repositories/badge_claim.repository.ts
  back-end/src/repositories/badge_owned.repository.ts
  back-end/src/repositories/employee_otp.repository.ts
  back-end/src/repositories/gym.repository.ts
  back-end/src/repositories/gym_brand.repository.ts
  back-end/src/repositories/gym_employee.repository.ts
  back-end/src/repositories/gym_owned.repository.ts
  back-end/src/repositories/gym_owner.repository.ts
  back-end/src/repositories/gym_user.repository.ts
  back-end/src/repositories/owner_otp.repository.ts
  back-end/src/repositories/user_otp.repository.ts
  back-end/src/users/users.test.ts
  back-end/src/users/users.ts
  back-end/src/utils/utils.ts
Labels: priority:high, scope:api, scope:db, status:not-ready, status:ready, type:change

#266 Feature Forgot Password
  front-end/src/App.tsx
  front-end/src/components/Register/Password.tsx
  front-end/src/components/Register/RegisterForm.tsx
  front-end/src/pages/ForgotPassword/ForgotPassword.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/OTP/OTP.css
  front-end/src/pages/OTP/OTP.tsx
  front-end/src/pages/ResetPassword/ResetPassword.tsx
  front-end/src/theme/variables.css
Labels: priority:high, scope:db, scope:ui, status:needs-tests, type:feature

#268 Update Integration Branch
  front-end/google-services.json
  front-end/gradleBuild.sh
  front-end/src/App.tsx
  front-end/src/components/Register/Password.tsx
  front-end/src/components/Register/RegisterForm.tsx
  front-end/src/pages/ForgotPassword/ForgotPassword.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/OTP/OTP.css
  front-end/src/pages/OTP/OTP.tsx
  front-end/src/pages/ResetPassword/ResetPassword.tsx
  front-end/src/theme/variables.css
  front-end/tsconfig.json
Labels: priority:low, status:ready, type:chore, scope:admin

#267 Feature Friends
  front-end/src/App.tsx
  front-end/src/components/FriendRequestsList/FriendRequestList.tsx
  front-end/src/components/FriendsList/FriendsList.tsx
  front-end/src/components/Register/Gym.tsx
  front-end/src/components/Register/Password.tsx
  front-end/src/pages/Explore/Explore.tsx
  front-end/src/pages/FriendProfile/FriendProfile.tsx
  front-end/src/pages/FriendRequests/FriendRequests.tsx
  front-end/src/pages/FriendsPage/FriendsPage.tsx
  front-end/src/pages/Leaderboard/Leaderboard.tsx
  front-end/src/pages/NotFriendProfile/NotFriendProfile.tsx
  front-end/src/pages/UserMap/UserMap.tsx
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/theme/variables.css
Labels: priority:high, scope:ui, status:needs-tests, type:feature

#269 Update with current heroku server!
  back-end/src/entities/gym.entity.ts
  back-end/src/entities/gym_brand.entity.ts
  back-end/src/entities/gym_employee.entity.ts
  back-end/src/entities/gym_owner.entity.ts
  back-end/src/entities/gym_user.entity.ts
  back-end/src/repositories/friend.repository.ts
  back-end/src/repositories/gym_user.repository.ts
  back-end/src/users/users.test.ts
  back-end/src/users/users.ts
Labels: priority:low, scope:api, status:needs-tests, type:change

#264 Feature Push Notifications
  back-end/src/users/users.ts
  front-end/capacitor.config.ts
  front-end/gradleBuild.sh
  front-end/package.json
  front-end/src/App.test.tsx
  front-end/src/App.tsx
  front-end/src/components/BurgerMenu/BurgerMenu.test.tsx
  front-end/src/components/Push/Push.tsx
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/SplashPage/SplashPage.test.tsx
  front-end/src/pages/SplashPage/SplashPage.tsx
  front-end/src/pages/UserMap/UserMap.tsx
  front-end/tsconfig.json
  gradleBuild.sh
  package.json
Labels: priority:medium, scope:api, scope:ui, status:not-ready, type:enhance, type:feature

#263 Added Tests
  front-end/src/components/Register/Contact.test.tsx
  front-end/src/components/Register/Gym.test.tsx
  front-end/src/components/Register/Identifications.test.tsx
  front-end/src/components/Register/Password.test.tsx
  front-end/src/components/Register/RegisterForm.test.tsx
  front-end/src/pages/AddGym/AddGym.test.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.test.tsx
  front-end/src/pages/CreateUserPage/Register.test.tsx
  front-end/src/pages/LoginPage/Login.test.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/ResetPassword/ResetPassword.test.tsx
Labels: priority:high, status:ready, type:change, type:chore, type:test, scope:admin, needs review!

#271 Create LICENSE
  LICENSE
Labels: type:documentation, priority:low, status:ready, type:chore, scope:admin

#273 Fixed Bug by changing pxt to px
  front-end/src/components/map/MapView.css
Labels: type:bug, priority:low, scope:ui, status:ready, type:change

#275 Form Validation and UI updates
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
  front-end/src/components/ActivityList/ActivityList.test.tsx
  front-end/src/components/BadgeCanvas/BadgeCanvas.test.tsx
  front-end/src/components/BadgeImage/BadgeImage.test.tsx
  front-end/src/components/BadgeSlider/BadgeSlider.test.tsx
  front-end/src/components/BadgeSuggestions/BadgeSuggestions.tsx
  front-end/src/components/EmployeeList/EmployeeList.test.tsx
  front-end/src/components/GymCard/GymCard.test.tsx
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.test.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.test.tsx
  front-end/src/components/GymsList/GymItem/GymItem.tsx
  front-end/src/components/LeaderBoardSwiper/LeaderBoardValues/LeaderboardValues.test.tsx
  front-end/src/components/LeaderBoardSwiper/LeaderboardSwiper.test.tsx
  front-end/src/components/MyBadgeGrid/MyBadgeCard/MyBadgeCard.test.tsx
  front-end/src/components/MyBadgeGrid/MyBadgeGrid.test.tsx
  front-end/src/components/PendingBadgeItem/PendingBadgeItem.test.tsx
  front-end/src/components/Register/Contact.tsx
  front-end/src/components/activityInputs/ActivityInputs.test.tsx
  front-end/src/components/activityInputs/ActivityInputs.tsx
  front-end/src/components/approvalButton/approvalButton.test.tsx
  front-end/src/components/dropdown/dropdown.test.tsx
  front-end/src/components/dropdown/dropdown.tsx
  front-end/src/components/filechooser/FileChooser.test.tsx
  front-end/src/components/map/MapView.test.tsx
  front-end/src/components/radioGroup/radioGroup.test.tsx
  front-end/src/components/radioGroup/radioGroup.tsx
  front-end/src/pages/AddEmployee/AddEmployee.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/EditGymPage/EditGym.tsx
  front-end/src/pages/Explore/Explore.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
  front-end/src/pages/MyGyms/MyGyms.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/theme/variables.css
Labels: priority:medium, scope:ui, status:needs-tests, type:cosmetic, type:enhance, type:feature

#270 Finishing Push Notifications and General Debugging
  front-end/package.json
  front-end/src/components/AR/AR.tsx
  front-end/src/components/AR/compatibleDevices.tsx
  front-end/src/components/BurgerMenu/BurgerMenu.tsx
  front-end/src/components/FriendRequestsList/FriendRequestList.tsx
  front-end/src/components/GymsList/GymItem/GymItem.tsx
  front-end/src/components/Register/Gym.tsx
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/components/map/MapView.css
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/AddEmployee/AddEmployee.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/Explore/Explore.tsx
  front-end/src/pages/FriendsPage/FriendsPage.tsx
  front-end/src/pages/NotFriendProfile/NotFriendProfile.tsx
  front-end/src/pages/SplashPage/SplashPage.tsx
  front-end/src/pages/UserMap/UserMap.css
  front-end/src/pages/UserMap/UserMap.tsx
  front-end/trapeze.yml
  package.json
Labels: priority:medium, scope:ui, status:needs-tests, status:on-hold, type:feature

#279 Debugging
  front-end/src/components/FriendRequestsList/FriendRequestList.tsx
  front-end/src/components/GymsList/GymsList.tsx
  front-end/src/pages/FriendsPage/FriendsPage.tsx
  front-end/src/pages/GymPage/GymPage.tsx
Labels: type:bug, priority:high, scope:ui, status:on-hold, type:fix

#280 Bug Fixes
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/FriendRequestsList/FriendRequestList.tsx
  front-end/src/components/GymCard/GymCard.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.tsx
  front-end/src/components/GymsList/GymItem/GymItem.tsx
  front-end/src/components/Register/Gym.tsx
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/AddEmployee/AddEmployee.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/EditGymPage/EditGym.tsx
  front-end/src/pages/EmployeeHomePage/EmployeeHome.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/EmployeeProfileView/EmployeeProfileView.tsx
  front-end/src/pages/Explore/Explore.tsx
  front-end/src/pages/ForgotPassword/ForgotPassword.tsx
  front-end/src/pages/FriendProfile/FriendProfile.tsx
  front-end/src/pages/FriendsPage/FriendsPage.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/GymOwnerPage/GymOwnerPage.tsx
  front-end/src/pages/GymPage/GymPage.tsx
  front-end/src/pages/Leaderboard/Leaderboard.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/pages/ManageEmployees/ManageEmployees.tsx
  front-end/src/pages/ManageGyms/ManageGyms.tsx
  front-end/src/pages/MyBadge/MyBadge.tsx
  front-end/src/pages/MyGyms/MyGyms.tsx
  front-end/src/pages/NotFriendProfile/NotFriendProfile.tsx
  front-end/src/pages/OwnerProfile/OwnerProfile.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/ResetPassword/ResetPassword.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/UserPendingBadges/PendingBadges.tsx
  front-end/src/pages/UserProfile/UserProfile.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
  front-end/src/theme/variables.css
Labels: priority:high, scope:ui, status:needs-tests, type:fix

#276 🔒️🧱✅Major back-end apikey refactor.
  back-end/src/employees/employees.test.ts
  back-end/src/employees/employees.ts
  back-end/src/entities/friend.entity.ts
  back-end/src/entities/gym_employee.entity.ts
  back-end/src/entities/gym_owner.entity.ts
  back-end/src/entities/gym_user.entity.ts
  back-end/src/entities/subscription.entity.ts
  back-end/src/owners/owners.test.ts
  back-end/src/owners/owners.ts
  back-end/src/repositories/badge.repository.ts
  back-end/src/repositories/badge_claim.repository.ts
  back-end/src/repositories/badge_owned.repository.ts
  back-end/src/repositories/friend.repository.ts
  back-end/src/repositories/gym.repository.ts
  back-end/src/repositories/gym_employee.repository.ts
  back-end/src/repositories/gym_owner.repository.ts
  back-end/src/repositories/gym_user.repository.ts
  back-end/src/repositories/subscription.repository.ts
  back-end/src/users/users.test.ts
  back-end/src/users/users.ts
  back-end/src/utils/utils.ts
Labels: priority:high, scope:api, status:ready, type:refactor

#278 API fixes on front-end
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/EmployeeProfile/EmployeeProfile.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
Labels: priority:high, scope:ui, status:ready, type:fix
