Repository COS301-SE-2022/Gym-King, pull requests merged in 2022-05, with the labels that each got.

#3 Create Monorepo with front and backend
  back-end/index.js
  back-end/package.json
  back-end/yarn.lock
  front-end/.gitignore
  front-end/README.md
  front-end/package.json
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/App.test.js
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/logo.svg
  front-end/src/reportWebVitals.js
  front-end/src/setupTests.js
  front-end/yarn.lock
  package.json
  packages/config/index.js
  packages/config/package.json
  yarn.lock
Labels: help wanted

#4 🧱 Small change to back-end and add gitignore.
  .gitignore
  back-end/index.js
Labels: enhancement, role:API Engineer, priority:low, scope:api, status:not-ready, type:enhance

#5 ✨ (UI):add ionic framework to front-end
  front-end/.gitignore
  front-end/README.md
  front-end/capacitor.config.ts
  front-end/ionic.config.json
  front-end/package.json
  front-end/public/assets/icon/favicon.png
  front-end/public/assets/icon/icon.png
  front-end/public/assets/shapes.svg
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/App.test.js
  front-end/src/App.test.tsx
  front-end/src/App.tsx
  front-end/src/components/ExploreContainer.css
  front-end/src/components/ExploreContainer.tsx
  front-end/src/index.css
  front-end/src/index.js
  front-end/src/index.tsx
  front-end/src/logo.svg
  front-end/src/pages/Home.css
  front-end/src/pages/Home.tsx
  front-end/src/react-app-env.d.ts
  front-end/src/reportWebVitals.ts
  front-end/src/service-worker.ts
  front-end/src/serviceWorkerRegistration.ts
  front-end/src/setupTests.js
  front-end/src/setupTests.ts
  front-end/src/theme/variables.css
  front-end/tsconfig.json
  front-end/yarn.lock
  package.json
  yarn.lock
Labels: enhancement, help wanted, role:UI Engineer, priority: high, scope:repository, scope:UI, status:needs-info, type:change

#6 👷 workflows and CI/CD
  .github/workflows/index.yml
  .github/workflows/metatest.yml
  .github/workflows/nxtest.yml
  .gitignore
  front-end/package.json
  nx.json
  package.json
  yarn.lock
Labels: role:tester, priority:medium, role:developer-operations, scope:repository, status:on-hold, type:refactor

#8 ✨ Update global themes to match color palette
  front-end/src/theme/variables.css
Labels: enhancement, role:ui-engineer, priority:low, scope:design, scope:ui, status:ready, type:cosmetic

#11 Created UI components
  front-end/src/App.tsx
  front-end/src/components/dropdown/dropdown.css
  front-end/src/components/dropdown/dropdown.tsx
  front-end/src/components/filechooser/FileChooser.css
  front-end/src/components/filechooser/FileChooser.tsx
  front-end/src/components/toolbar/Toolbar.css
  front-end/src/components/toolbar/Toolbar.tsx
  front-end/src/pages/Home.css
  front-end/src/pages/Home.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.css
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/theme/variables.css
  package.json
  yarn.lock
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:ready, type:feature

#12 Feature map
  capacitor.config.ts
  package.json
  yarn.lock
Labels: role:ui-engineer, priority:low, role:developer-operations, scope:repository, scope:ui, status:on-hold, type:change, type:refactor

#13 Feature map
  testingFile
Labels: priority: high, priority:medium, role:developer-operations, scope:cicd, scope:repository, status:ready, type:test

#14 test
  testingFile
Labels: role:tester, priority:medium, scope:cicd, scope:ui, status:ready, type:test

#15 Add UploadActivityPage
  front-end/src/App.tsx
  front-end/src/components/dropdown/dropdown.tsx
  front-end/src/pages/Home.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.css
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/theme/variables.css
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:feature

#22 Updated UploadActivityPage
  Test.txt
  front-end/src/App.tsx
  front-end/src/components/activityInputs/ActivityInputs.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.css
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/theme/variables.css
  yarn.lock
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:feature

#23 Added new ApprovalButton component
  front-end/src/components/approvalButton/approvalButton.css
  front-end/src/components/approvalButton/approvalButton.tsx
  front-end/src/pages/Home.tsx
  front-end/src/theme/variables.css
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:feature

#25 Updated ApprovalButton
  front-end/src/components/approvalButton/approvalButton.css
  front-end/src/components/approvalButton/approvalButton.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:enhance, type:feature

#24 ✨ (UI) Add AddGymPage
  front-end/public/index.html
  front-end/src/App.tsx
  front-end/src/pages/AddGym/AddGym.css
  front-end/src/pages/AddGym/AddGym.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:ready, type:feature

#16 Add AcceptReject
  front-end/src/pages/AcceptRejectPage/AcceptReject.css
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
Labels: role:ui-engineer, role:designer, priority:medium, scope:client, scope:design, scope:ui, status:ready, type:feature

#28 Adding PendingApprovalsPage
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.css
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:feature

#29 (UI): Intergrated Map to the AddGym Feature
  front-end/src/App.tsx
  front-end/src/components/map/MapView.css
  front-end/src/components/map/MapView.tsx
  front-end/src/components/pigeonMaps/pigeonMap.css
  front-end/src/components/pigeonMaps/pigeonMap.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.css
  front-end/src/pages/AddGymLocation/AddGymLocation.tsx
  package.json
  yarn.lock
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:ready, type:feature

#30 Added components
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.css
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/ActivityList/ActivityList.tsx
  front-end/src/pages/Home.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:feature

#31 Updated AcceptRejectPage
  front-end/src/App.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.css
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:feature

#33 Added Navigation
  front-end/src/App.tsx
  front-end/src/components/approvalButton/approvalButton.css
  front-end/src/components/approvalButton/approvalButton.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.css
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:feature

#34 Updated Navigation
  front-end/src/components/approvalButton/approvalButton.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:feature

#35 Updated API calls
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:enhance

#40 (UI):added basic functionality to maps
  front-end/src/components/SelectGym-Map/SelectGymMap.css
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/components/pigeonMaps/pigeonMap.css
  front-end/src/components/pigeonMaps/pigeonMap.tsx
  front-end/src/pages/AddGym/AddGym.css
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.css
  front-end/src/pages/AddGymLocation/AddGymLocation.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:ready, type:enhance

#39 Created Unit Test for UploadActivityPage
  front-end/src/pages/UploadActivityPage/UploadActivityPage.test.tsx
Labels: enhancement, role:ui-engineer, role:tester, priority:medium, scope:ui, status:not-ready, type:test

#37 Added POST to AddGym
  front-end/src/pages/AddGym/AddGym.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:feature

#41 (UI) Feature map
  front-end/src/App.tsx
  front-end/src/components/map/MapView.css
  front-end/src/components/map/MapView.tsx
  front-end/src/pages/UserMap/UserMap.tsx
  package.json
  yarn.lock
Labels: role:ui-engineer, priority:medium, scope:ui, status:ready, type:feature

#42 🩹 fixed map-icon positioning with an overlay
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/pages/AddGym/AddGym.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.css
  front-end/src/pages/AddGymLocation/AddGymLocation.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:ready, type:fix

#45 Added Validation
  front-end/src/components/activityInputs/ActivityInputs.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.css
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/validation/UploadClaimValidation.tsx
  package.json
  yarn.lock
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:feature

#47 Added Unit Tests to Pages
  front-end/src/pages/AcceptRejectPage/AcceptRejectPage.test.tsx
  front-end/src/pages/AddGym/AddGym.test.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.test.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.test.tsx
Labels: enhancement, role:tester, priority:medium, scope:ui, status:ready, type:test

#49 Added Unit Tests for components
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
  front-end/src/components/ActivityList/ActivityList.test.tsx
  front-end/src/components/activityInputs/ActivityInputs.test.tsx
  front-end/src/components/approvalButton/approvalButton.test.tsx
  front-end/src/components/filechooser/FileChooser.test.tsx
  front-end/src/components/toolbar/Toolbar.test.tsx
  front-end/src/pages/UserMap/UserMap.test.tsx
Labels: enhancement, role:ui-engineer, role:tester, priority:medium, scope:ui, status:ready, type:test

#50 ✨ Add AddGym API Call
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/pages/AddGym/AddGym.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:api, scope:ui, status:ready, type:feature

#55 ✨ Added geocoding API
  front-end/src/components/SelectGym-Map/SelectGymMap.tsx
  front-end/src/pages/AddGym/AddGym.css
  front-end/src/pages/AddGym/AddGym.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:not-ready, type:enhance

#56 🚑 Fixed coordinate errors, when adjusting coordinates
  front-end/src/pages/AddGym/AddGym.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:ready, type:fix

#57 Feature/server
  back-end/.gitignore
  back-end/gymkingheroku.test.js
  back-end/gymkingheroku.ts
  back-end/index.js
  back-end/package.json
  back-end/yarn.lock
  yarn.lock
Labels: good first issue, role:service-engineer, priority:high, scope:api, status:on-hold, status:ready, type:feature

#58 Feature/server
  back-end/Procfile
  back-end/gymkingheroku.ts
  back-end/package.json
  package.json
Labels: role:service-engineer, priority:high, scope:api, scope:repository, status:ready, type:chore

#60 Updated Unit Test
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
Labels: enhancement, role:ui-engineer, role:tester, priority:low, scope:ui, status:needs-tests, type:feature

#63 💄 (UI): added toast 🍞
  front-end/src/pages/AddGym/AddGym.tsx
Labels: enhancement, role:ui-engineer, priority:high, priority:low, scope:ui, status:ready, type:cosmetic, type:feature

#64 Update Unit Tests
  front-end/src/components/approvalButton/approvalButton.test.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:feature

#65 🧱 Changes to server APIs
  back-end/gymkingheroku.ts
Labels: enhancement, role:service-engineer, role:api-engineer, priority:medium, scope:api, status:ready, type:enhance

#66 Added API updates
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/ActivityList/ActivityList.css
  front-end/src/components/ActivityList/ActivityList.tsx
  front-end/src/components/approvalButton/approvalButton.tsx
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
Labels: enhancement, role:ui-engineer, priority:high, scope:api, scope:ui, status:needs-tests, type:feature

#67 💄 (UI): Added toast to upload activity page 🍞🍞
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:ready, type:cosmetic

#68 Updated API calls
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
Labels: enhancement, role:ui-engineer, priority:high, scope:api, scope:ui, status:needs-tests, type:enhance, type:feature

#70 Added Navigation
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  package.json
  yarn.lock
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:feature

#71 Updated FileChooser
  front-end/src/components/filechooser/FileChooser.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:feature

#72 🩹 Changed coordinate variables
  front-end/src/pages/AddGym/AddGym.tsx
Labels: enhancement, role:ui-engineer, priority:high, scope:ui, status:ready, type:fix

#86 Created CreateButtonPage
  front-end/src/App.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/theme/variables.css
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:feature

#87 Adding EditBadge page
  front-end/src/App.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.css
  front-end/src/theme/variables.css
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:feature
