Repository COS301-SE-2022/Gym-King, pull requests merged in 2022-06, with the labels that each got.

#89 Updated the EditBadge page
  front-end/src/pages/EditBadgePage/EditBadge.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:enhance, type:feature

#88 CreateBadge updated
  front-end/src/components/dropdown/dropdown.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/validation/CreateBadgeValidation.tsx
Labels: enhancement, role:ui-engineer, priority:high, priority:medium, scope:ui, status:needs-tests, type:enhance, type:feature

#92 Feature api
  back-end/.gitignore
  back-end/Procfile
  back-end/gymkingheroku.test.js
  back-end/gymkingheroku.test.ts
  back-end/gymkingheroku.ts
  back-end/index.ts
  back-end/jest.config.js
  back-end/package-lock.json
  back-end/package.json
  package.json
  yarn.lock
Labels: enhancement, role:api-engineer, priority:high, scope:api, status:not-ready, type:feature, type:test

#94 ✅ Added Post API tests.
  back-end/gymkingheroku.test.ts
Labels: enhancement, role:api-engineer, priority:low, scope:api, status:not-ready, type:test

#95 🧱 ✅ Added Post API tests and changed JSON return.
  back-end/gymkingheroku.test.ts
  back-end/gymkingheroku.ts
Labels: enhancement, role:api-engineer, priority:low, scope:api, status:not-ready, type:test

#96 (UI): Feature-view badges :make layout for the view badges page
  front-end/src/App.tsx
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.css
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.css
  front-end/src/pages/ViewBadgePage/ViewBadgePage.test.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
  front-end/src/utils/badges.json
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:not-ready, type:feature

#99 Updated EditBadge Page
  front-end/src/components/dropdown/dropdown.tsx
  front-end/src/components/segmentButton/segmentButton.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/EditBadgePage/edit.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:enhance

#100 Updated CreateBadge Page
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/EditBadgePage/edit.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:fix

#115 Updated EditBadge Page
  front-end/src/pages/EditBadgePage/EditBadge.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, type:cosmetic

#119 Updated Test Files
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
  front-end/src/components/ActivityList/ActivityList.test.tsx
  front-end/src/components/activityInputs/ActivityInputs.test.tsx
  front-end/src/components/approvalButton/approvalButton.test.tsx
  front-end/src/components/dropdown/dropdown.test.tsx
  front-end/src/components/filechooser/FileChooser.test.tsx
  front-end/src/components/map/MapView.test.tsx
Labels: enhancement, role:tester, priority:low, scope:ui, status:needs-tests, type:enhance

#120 Updated CreateBadge page
  front-end/src/components/radioGroup/radioGroup.tsx
  front-end/src/components/segmentButton/segmentButton.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/theme/variables.css
  front-end/src/validation/CreateBadgeValidation.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:enhance, type:feature

#121 (UI)Feature view badges for gym-goer : Complete View Badge layout
  front-end/src/App.tsx
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.css
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.css
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
  front-end/src/utils/badges.json
Labels: enhancement, role:ui-engineer, priority:high, scope:ui, status:ready, type:feature

#123 ✨ (UI) : Create ViewBadge page for GymOwners
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGri.css
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.css
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
Labels: enhancement, role:ui-engineer, priority:high, scope:ui, status:needs-tests, type:feature

#122 Updated EditBadge page
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:enhance, type:feature

#125 ✨ (UI)view badges : Fix Grid Spacing and styling for narrower screens
  front-end/src/components/GymOwner-ViewBadgeGrid/GymOwnerViewBadgeGrid.tsx
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.css
  front-end/src/components/GymOwner-ViewBadgeGrid/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.css
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.test.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.tsx
Labels: enhancement, role:ui-engineer, priority:high, scope:ui, status:needs-tests, type:cosmetic, type:enhance

#126 Fixed EditBadge Page
  front-end/src/components/segmentButton/segmentButton.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
Labels: enhancement, role:ui-engineer, priority:medium, scope:ui, status:needs-tests, type:enhance, type:fix

#127 Fixed GetRequests
  front-end/src/pages/AcceptRejectPage/AcceptReject.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.tsx
  front-end/src/pages/EditBadgePage/EditBadge.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.tsx
  front-end/src/validation/CreateBadgeValidation.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:needs-tests, status:next-release, type:fix

#128 Updated Unit Tests
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.test.tsx
  front-end/src/components/ActivityList/ActivityList.test.tsx
  front-end/src/components/activityInputs/ActivityInputs.test.tsx
  front-end/src/components/approvalButton/approvalButton.test.tsx
  front-end/src/components/dropdown/dropdown.test.tsx
  front-end/src/components/dropdown/dropdown.tsx
  front-end/src/components/filechooser/FileChooser.test.tsx
Labels: enhancement, role:tester, priority:medium, scope:ui, status:needs-tests, status:ready, type:test

#132 🎨 🧱 drop tables API fixed. Restructured.
  back-end/Models/chair_swan.usdz
  back-end/Models/concept.glb
  back-end/Models/melee.glb
  back-end/Models/melee.usdz
  back-end/index.ts
  back-end/utils/utils.test.ts
  back-end/utils/utils.ts
Labels: enhancement, role:service-engineer, role:api-engineer, priority:low, scope:api, scope:db, status:ready, type:enhance

#133 Feature Login
  front-end/src/App.tsx
  front-end/src/pages/LoginPage/Login.css
  front-end/src/pages/LoginPage/Login.tsx
Labels: role:designer, priority:low, scope:client, status:ready, type:enhance

#135 (UI) added some testing for the leaderboard page
  front-end/src/pages/AddGym/AddGym.test.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.test.tsx
  front-end/src/pages/AddGymLocation/AddGymLocation.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.test.tsx
Labels: enhancement, role:tester, priority:high, scope:ui, status:ready, type:test

#137 ✅ 🧱 Adding API and Test for it.
  back-end/users/users.test.ts
  back-end/users/users.ts
Labels: enhancement, role:service-engineer, role:api-engineer, priority:medium, scope:api, status:ready, type:feature

#139 ✨ (UI) Leaderboards - Implement Api
  front-end/src/components/LeaderBoardSwiper/LeaderBoardValues/LeaderboardValues.tsx
  front-end/src/components/LeaderBoardSwiper/LeaderboardSwiper.tsx
  front-end/src/pages/Leaderboard/Leaderboard.tsx
Labels: enhancement, role:ui-engineer, priority:high, scope:ui, status:ready, type:feature

#140 💅 (UI) fixed styling
  front-end/src/components/LeaderBoardSwiper/LeaderBoardValues/LeaderboardValues.css
  front-end/src/components/LeaderBoardSwiper/LeaderBoardValues/LeaderboardValues.tsx
  front-end/src/components/LeaderBoardSwiper/LeaderboardSwiper.tsx
Labels: enhancement, role:ui-engineer, priority:high, scope:design, scope:ui, status:ready, type:cosmetic

#141 Added Integration Tests
  front-end/src/components/AcceptRejectCard/AcceptRejectCard.tsx
  front-end/src/components/activityInputs/ActivityInputs.tsx
  front-end/src/components/approvalButton/approvalButton.tsx
  front-end/src/components/radioGroup/radioGroup.tsx
  front-end/src/components/segmentButton/segmentButton.tsx
  front-end/src/components/toolbar/Toolbar.tsx
  front-end/src/pages/AcceptRejectPage/AcceptRejectPage.test.tsx
  front-end/src/pages/CreateBadgePage/CreateBadge.test.tsx
  front-end/src/pages/EditBadgePage/EditBadge.test.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.test.tsx
  front-end/src/pages/PendingApprovalsPage/PendingApprovalsPage.tsx
  front-end/src/pages/UploadActivityPage/UploadActivityPage.test.tsx
Labels: enhancement, role:ui-engineer, role:tester, priority:high, priority:medium, scope:ui, status:needs-tests, status:ready, type:test

#143 🧪 (Testing):Feature leaderboard -add some tests
  front-end/src/components/LeaderBoardSwiper/LeaderboardSwiper.tsx
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.test.tsx
  front-end/src/components/ViewBadgeCard/ViewBadgeCard.tsx
  front-end/src/pages/GymOwner-ViewBadge/GymOwnerViewBadge.test.tsx
  front-end/src/pages/Leaderboard/Leaderboard.test.tsx
  front-end/src/pages/Leaderboard/Leaderboard.tsx
  front-end/src/pages/ViewBadgePage/ViewBadgePage.test.tsx
Labels: enhancement, role:tester, priority:high, scope:ui, status:ready, type:test

#144 Fix EditBadge
  front-end/src/pages/EditBadgePage/EditBadge.tsx
Labels: enhancement, role:ui-engineer, priority:low, scope:ui, status:ready, type:fix

#134 Feature login
  back-end/.gitignore
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/pages/CreateUserPage/CreateUserPage.css
  front-end/src/pages/CreateUserPage/CreateUserPage.tsx
  front-end/src/pages/LoginPage/Login.tsx
  front-end/src/validation/CreateBadgeValidation.tsx
  front-end/src/validation/CreateUserValidation.tsx
  package.json
  yarn.lock
Labels: enhancement, role:ui-engineer, role:designer, role:api-engineer, priority:medium, scope:api, scope:client, scope:design, scope:ui, status:ready, type:enhance, type:feature
